name: ITT_env
channels:
  - conda-forge
  - defaults
dependencies:
  # --- core, portable conda deps ---
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - tqdm

  # --- python packages that are fine via pip on all OSes ---
  - pip:
      - torch>=2.2
      - torchvision>=0.17
      - torchaudio>=2.2
      - gudhi==3.11.0
      - pymatgen==2025.6.14
      - bitarray==3.4.2
